import { ROLE_CODES } from "@/lib/auth/constants";

export const LEGACY_WORKSPACE_ROLES = [ROLE_CODES.OWNER, ROLE_CODES.MANAGER] as const;

export const LEGACY_WORKSPACE_VIEW_ROLES = [
  ROLE_CODES.OWNER,
  ROLE_CODES.MANAGER,
  ROLE_CODES.CONSULTANT,
  ROLE_CODES.INSTALLER,
] as const;
